version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
          test: [ "CMD", "nc", "-z", "localhost", "5672" ]
          interval: 5s
          timeout: 15s
          retries: 1
  monolito-service:
    image: monolito-service
    container_name: monolito-service
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
