version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: myrabbit
    ports:
      - 5672:5672
      - 15672:15672
  monolito-service:
    image: monolito-service
    container_name: monolito-service
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
  lending-service:
    image: lending-service
    container_name: lending-service
    ports:
      - 8081:8081
  notification-service:
    image: notification-service
    container_name: notification-service
    ports:
      - 8082:8082

